services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file: docker.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  postgres:
    image: postgres:13.1
    container_name: postgres
    restart: always
    env_file: docker.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_LOCAL_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  default_worker:
    build:
      context: .
    container_name: worker
    restart: always
    depends_on:
      - redis
      - postgres
    env_file: docker.env
    command: poetry run saq worker.run_worker.worker_settings --web
    networks:
      - app_network
    ports:
      - "8080:8080"

  bot:
    build: .
    container_name: bot
    restart: always
    command: poetry run python main.py
    depends_on:
      - redis
      - postgres
    env_file:
      - docker.env
    networks:
      - app_network

volumes:
  redis_data:
  postgres_data:

networks:
  app_network:
    driver: bridge