"""add pet column

Revision ID: 1984111c034b
Revises: b96ae37e6fb5
Create Date: 2025-02-20 21:47:39.037447

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1984111c034b'
down_revision: Union[str, None] = 'b96ae37e6fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'pet', ['company_id'])
    op.create_foreign_key(None, 'pet', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.drop_constraint(None, 'pet', type_='unique')
    op.drop_column('pet', 'company_id')
    # ### end Alembic commands ###
