"""made fields date optional

Revision ID: cc1fdcfeced8
Revises: 1984111c034b
Create Date: 2025-02-20 21:52:18.145493

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc1fdcfeced8'
down_revision: Union[str, None] = '1984111c034b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'Дата рождения',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('pet', 'Дата приобретения',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'Дата приобретения',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.alter_column('pet', 'Дата рождения',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    # ### end Alembic commands ###
