"""added constraint

Revision ID: c85cace628c1
Revises: cc1fdcfeced8
Create Date: 2025-02-23 22:09:13.461078

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c85cace628c1'
down_revision: Union[str, None] = 'cc1fdcfeced8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pet_company_id_key', 'pet', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pet_company_id_key', 'pet', ['company_id'])
    # ### end Alembic commands ###
