"""added feeding model

Revision ID: d9b331125a35
Revises: c85cace628c1
Create Date: 2025-03-06 22:36:11.049103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b331125a35'
down_revision: Union[str, None] = 'c85cace628c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('Дата кормления', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_food', sa.Float(), nullable=True),
    sa.Column('Единица измерения', sa.Enum('GRAM', 'KILOGRAM', 'QUANTITY', 'MISS', name='measureunitfood'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('Дата обновления', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('group_company_id_key', 'group', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('group_company_id_key', 'group', ['company_id'])
    op.drop_table('feeding_pet')
    # ### end Alembic commands ###
