"""added time zone and language 

Revision ID: 0a01bacf17fe
Revises: d9b331125a35
Create Date: 2025-03-08 19:14:08.995593

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0a01bacf17fe'
down_revision: Union[str, None] = 'd9b331125a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Регион', sa.String(), nullable=True))
    op.add_column('users', sa.Column('Cмещение пояса', sa.String(), nullable=True))
    op.add_column('users', sa.Column('Долгота', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('Широта', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'Широта')
    op.drop_column('users', 'Долгота')
    op.drop_column('users', 'Cмещение пояса')
    op.drop_column('users', 'Регион')
    # ### end Alembic commands ###
