"""changed the field type

Revision ID: 0a88c4aec06e
Revises: 0a01bacf17fe
Create Date: 2025-03-11 21:07:54.617725

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0a88c4aec06e'
down_revision: Union[str, None] = '0a01bacf17fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'Cмещение пояса',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='"Cмещение пояса"::integer',
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'Cмещение пояса',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
