"""added model feeding schedule

Revision ID: c8d10e50d872
Revises: 0a88c4aec06e
Create Date: 2025-04-01 21:32:12.321692

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8d10e50d872"
down_revision: Union[str, None] = "0a88c4aec06e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feeding_schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("Дата кормления", sa.DateTime(timezone=True), nullable=False),
        sa.Column("Активен?", sa.Boolean(), nullable=False),
        sa.Column("Напомнить?", sa.Boolean(), nullable=True),
        sa.Column(
            "Дата добавления",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feeding_schedules_Дата кормления"),
        "feeding_schedules",
        ["Дата кормления"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_feeding_schedules_Дата кормления"), table_name="feeding_schedules"
    )
    op.drop_table("feeding_schedules")
    # ### end Alembic commands ###
